version: '3.3'

services:
  api:
    image: golang:latest
    volumes:
     - .:/go/src/reddit_api
    working_dir: /go/src/reddit_api/
    command: go run main.go
    container_name: 'reddit_api'
    ports:
     - '8080:8080'
    env_file:
     - private.env
    depends_on:
     - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
     - '27100:27017'
