version: '3.3'
services:
  api:
    build: './'
    container_name: 'reddit_api'
    ports:
     - '8080:8080'
    env_file:
     - private.env
    volumes:
     - './api:/go/src/reddit_api'
    depends_on:
     - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
     - '27100:27017'
